### PR TITLE
[Feat] Add Digital Input Adapter for Enhanced Menu Navigation

### PR DESCRIPTION
**Pull request by forntoh**
These commits introduces the following changes:

1. **Digital Input Adapter:**
   - Added a new `DigitalInputAdapter` class to handle various digital inputs for menu navigation.
   - Supports multiple types of digital inputs including buttons, switches, and other digital sensors.
   - Provides debouncing functionality for stable readings.

2. **Example Usage:**
   - Provided example sketch (`DigitalInputAdapter.ino`) demonstrating the usage of various digital inputs with the `LcdMenu`.
   - Added another example sketch (`DigitalInputWithRotaryAdapter.ino`) showing how `DigitalInputAdapter` can be used in conjunction with other input adapters like `SimpleRotaryAdapter`. This example demonstrates that double press actions, which are often not read properly, can be substituted with a dedicated button for more reliable input.

These changes enhance the flexibility and usability of the menu system by allowing various digital inputs to interact seamlessly with the menu.

### CODE REVIEW

**Comment by ShishkinDmitriy** [comment]
You can utilize something like that https://github.com/madleech/Button

**Comment by forntoh** [comment]
> You can utilize something like that https://github.com/madleech/Button

It's one less dependency for the user to install which is good, so I'm keeping it, had this problem #203 where dependencies are not installed automatically, fixed it by removing the line in properties file, they user will have to install it manually if it's not already installed.

**Comment by ShishkinDmitriy** [comment]
As improvement it could be nice to specify type of event for adapter:
`DigitalInputAdapter upBtn(&menu, 2, PRESSED, UP);`
With following possibilities:
- HIGH_LEVEL
- LOW_LEVEL
- PRESSED
- RELEASES
- HOLD
- DOUBLE_CLICK

Something like that. Maybe in different PR

**Review by ShishkinDmitriy — APPROVED** [review]

**Comment by forntoh** [comment]
> As improvement it could be nice to specify type of event for adapter: `DigitalInputAdapter upBtn(&menu, 2, PRESSED, UP);` With following possibilities:
> 
> * HIGH_LEVEL
> * LOW_LEVEL
> * PRESSED
> * RELEASES
> * HOLD
> * DOUBLE_CLICK
> 
> Something like that. Maybe in different PR

Actually, I don't really want it to be that complicated. It's meant to be an easy way to just bind it to the pin and execute call an action when it becomes HIGH.
I can still evaluate adding some of those later also if users request it.
If you see the example of `DigitalInputWithRotaryAdapter`, it works well when paired with another input method. If the the requirements of the dev restrict the dev from having only push buttons and not more than 4, then maybe double tap can be added so that instead of 4 (UP, DOWN, ENTER, BACKSPACE) you can use 2 (2 actions per BTN). In most cases you'll need only three buttons (UP, DOWN & ENTER).

**Pull request merged**
