### PR TITLE
Delegate Rendering of Separator and Value to Renderer

### PR DESCRIPTION
**Pull request by forntoh**
## Description

This PR refactors the rendering logic by delegating the responsibility of rendering separators and values from individual items to the MenuRenderer. The changes include:

- Moving the render logic from each item to the `MenuRenderer`. Allowing the `MenuRenderer` to decide how to render the value, enabling customization of the separator.
- This refactor enhances the flexibility and maintainability of the rendering process by centralizing the rendering logic within the `MenuRenderer`.

### Changes

- Updated `MenuRenderer` to handle the rendering of separators and values.
- Removed rendering logic from individual items.
- Also adjusted the way `view` works in `ItemInput`, now when backspaces is pressed while the view is scrolled, it moves the characters to the right immediately until view is zero, this fixes the situation in previous releases where when I start deleting the characters and I reach the colon, I can't see the next character I am deleting.

## Screenshots/Video (if applicable)

https://github.com/user-attachments/assets/d0be9af5-04a2-400d-83e2-9905a3ff3461

---

#### General Requirements

- [x] I have kept this PR in draft until all the required tasks are completed.
- [x] I have reviewed the [contributing guidelines](/CONTRIBUTING.md) for this project.
- [x] I have tagged this PR with `breaking-change` if it introduces a breaking change.
- [x] I have checked that this PR does not introduce any breaking changes unless explicitly stated.
- [x] I have checked that changes generate no new warnings.
- [x] I have performed a self-review of my own code
- [x] I have built and tested **ALL** the examples to ensure that I haven't broken anything.

#### Refactor/Enhancement

- [x] **This PR is a code refactor.**
- [x] I have tagged this PR with `enhancement`.
- [x] I have made changes to the code that improve readability/performance/maintainability.
- [x] I have added documentation for the changes if necessary.
- [x] I have [generated](/docs/README.md) and reviewed the documentation locally if necessary.

### CODE REVIEW

**Comment by ShishkinDmitriy** [comment]
> Moving the render logic from each item to the MenuRenderer. Allowing the MenuRenderer to decide how to render the value, enabling customization of the separator.

Think it's a bad idea.. `MenuRenderer` shouldn't decide how to render value, item should. I am trying to add change when item has multiple widgets and draw them. Now all responsibility goes to renderer, it's not right I think. In version 4 we moved logic from menu into items, now it moved from items but into renderer.

**Comment by forntoh** [comment]
> > Moving the render logic from each item to the MenuRenderer. Allowing the MenuRenderer to decide how to render the value, enabling customization of the separator.
> 
> Think it's a bad idea.. `MenuRenderer` shouldn't decide how to render value, item should. I am trying to add change when item has multiple widgets and draw them. Now all responsibility goes to renderer, it's not right I think. In version 4 we moved logic from menu into items, now it moved back from items but into renderer.

Delegating rendering to the `MenuRenderer` separates the concerns of data representation and rendering. Items focus on their data and behavior, while the renderer handles how they are displayed.

The new menu controls that you're add would still work, all you would need to do is to pass the`text` and the `value` which can be a concatenated string eg.

```
text = "Time"
value = "00:00:00"

text = "Distance"
value = "100 km"
```

This will get rendered appropriately like `Time:00:00:00` or `Distance:100 km`, the item doesn't need to decide how the text and the value should be rendered, it should just provide the `value` in the way it should be rendered and the renderer renders it. In summary the logic of concatenated the `Controls` still remains in the item, you will only have to play with the blinker position.

**Comment by ShishkinDmitriy** [comment]
What if I have small screen and I want to render
```Time:00:00``` on normal mode and 
```e:00:00:00``` on edit mode?
Your implementation of Renderer knows about concept of `text`, `value`, `separator` and holds code how to render it.
Why not just allow items to hold that concepts and know how to render them? Just pass to item a display where to render, start point and end point.

**Comment by forntoh** [comment]
> What if I have small screen and I want to render `Time:00:00` on normal mode and `e:00:00:00` on edit mode? Your implementation of Renderer knows about concept of `text`, `value`, `separator` and holds code how to render it. Why not just allow items to hold that concepts and know how to render them? Just pass to item a display where to render, start point and end point.

I am planning to open a new PR which will handle horizontal scrolling of the items so, it's still a WIP, so the issue of no small display will be effectively gone (Hopefully 😃)

And I I guess your example here is already the case for `ItemInput`, item input currently modifies how it is rendered by just passing the value as the text currently in view (you implemented that and nothing has changed there, it's still possible to render only what is visible)

**Comment by ShishkinDmitriy** [comment]
Check this out https://github.com/ShishkinDmitriy/LcdMenu/blob/feature/add-multidimentional-items/src/BaseItemManyWidgets.h#L50

**Comment by forntoh** [comment]
Here's a video of the WIP

https://github.com/user-attachments/assets/304cbe20-b7f3-4bd9-8cc4-e43f53453ae0

**Comment by ShishkinDmitriy** [comment]
Looks great! How it works with Rotary? It has no LEFT and Right commands.

**Comment by forntoh** [comment]
> Looks great! How it works with Rotary? It has no LEFT and Right commands.

I you have only a RotaryEncoder, you're out of luck 😃, you can't shift it by command, I am thinking of adding like a timed shift (but not in the same WIP), that someone can enable to automatically h-scroll items when they are in focus like an animation.

If items have the possibility to shift the view programatically (for display purposes) then all the cases I see in your WIP can be handled eg when using only a rotary encoder and I type a char I can decide to shift the whole view instead of just the view the value occupies.

**Comment by ShishkinDmitriy** [comment]
I did this way:

https://github.com/user-attachments/assets/9fc41c95-cfe1-4e20-a278-ea2cc82dc12a

Item has 3 slots, every time you ENTER control move to next, and draw method tries to draw it up to blinker. After ENTER on last widget, it release. So item controls what to show, also we can combine and allow LEFT and RIGHT, but if no such commands, blinker should control view

**Comment by forntoh** [comment]
> I did this way:
> 
>  Recording.2024-10-08.121622.mp4 
> Right now keep text maybe not a good idea, maybe show value would be better.
> 
> Item has 3 slots, every time you ENTER control move to next, and draw method tries to draw it up to blinker. After ENTER on last widget, it release. So item controls what to show, also we can combine and allow LEFT and RIGHT, but if no such commands, blinker should control view.

Looks really nice! Can't wait for that PR to be ready, will be a huge improvement.

I see it integrating well with my changes as the renderer provides the possibility to move the cursor and start/stop blinker, this would be implemented like you did in input item, you'll just need to play with the cursor position, calculate the available view space and then adjust the value to display before sending to the renderer, just like how iteminput currently does to shift texts when typing.

I see you wrote a lot of code (well commented 💪), and you unfortunately need to refactor a lot 😬 sorry!

**Review by ShishkinDmitriy — APPROVED** [review]

**Pull request merged**
