### PR TITLE
Inputs and display refactoring

### PR DESCRIPTION
**Pull request by ShishkinDmitriy**
Renamed `LiquidCrystalI2CAdapter` into `LiquidCrystal_I2CAdapter` to match wrapped class `LiquidCrystal_I2C`.
Don't create LCD instance inside adapter, just wrap existing, so calling code owns the implementation of LCD.
Regarding #45 if intance will be created outside, we can hide implementation.

### CODE REVIEW

**Comment by ShishkinDmitriy** [comment]
Don't understand why this PR contains changes from revious one...

**Comment by forntoh** [comment]
Because you didn't update your branch (merge changes from [forntoh:feature/move-control-to-items](https://github.com/forntoh/LcdMenu/tree/feature/move-control-to-items) into your forked branch

**Comment by ShishkinDmitriy** [comment]
Thanks, handled.

**Comment by ShishkinDmitriy** [comment]
I would also renamed directory `interface` into `display`, if you don't mind.

**Comment by forntoh** [comment]
I have rebased your branch, it now only has 2 commits instead of 31 as before

**Comment by forntoh** [comment]
History is messed up again 😃, next time, pull and rebase your local branch, or just merge from remote, doing a normal pull will mess up the history (for this specific branch)

Also, for future PRs, don't use the same base branch ShishkinDmitriy:move-logic-to-items, create a new one for every feature, the issue you faced with unknown commits won't happen again.

I will rebase to elliminate the duplicate commits.
[Delete your local branch first then check out the remote branch after]

**Review by forntoh — APPROVED** [review]

**Pull request merged**
