### PR TITLE
add backlight support for non-I2C

### LINKED ISSUE #21: Backlight support for non-I2C
I had to hack and add the last 2 parameters to `new LiquidCrystal` in order to get the backlight working.

```
#ifndef USE_STANDARD_LCD
        uint8_t lcd_Addr, MenuItem* menu) {
        lcd = new LiquidCrystal_I2C(lcd_Addr, maxCols, maxRows);
        lcd->init();
        lcd->backlight();
#else
        uint8_t rs, uint8_t en, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3,
        MenuItem* menu) {
        this->lcd = new LiquidCrystal(rs, en, d0, d1, d2, d3, DisplayBacklightPin, POSITIVE); // <---
        this->lcd->begin(maxCols, maxRows);
#endif
```

would be nice if this could be supported in the library.

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #21

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@forntoh this is how I implemented it, any suggestions for improvements are welcome.

**Comment by thijstriemstra** [comment]
updated PR and resolved conflicts.

**Comment by forntoh** [comment]
Thanks for your support @thijstriemstra, the reason why I haven't approved this yet is because the `LiquidCrystal` library you are using is not the one most people will use, the original `LiquidCrystal` from Arduino doesn't have a constructor with that additional argument, if this is merged, it won't compile for most users.

**Comment by forntoh** [comment]
Okay, one way to do it is to add the dependency you are using to `library.json` and `library.properties`, so that we can guarantee that users won't encounter any errors. Also, while doing that, please check if there the library can be included by users from the Arduino Library Manager and also make a copy of the basic example and make it work without I2C (there are checks that I have set up on GitHub)

**Pull request closed without merging**
