### PR TITLE
Replace SimpleNavConfig with KeyboardAdapter

### PR DESCRIPTION
**Pull request by forntoh**
Replaced SimpleNavConfig struct with KeyboardAdapter class for input handling. Updated code across multiple examples to utilize the new KeyboardAdapter for menu navigation and input processing.

### CODE REVIEW

**Comment by forntoh** [comment]
@ShishkinDmitriy I just noticed that the SubMenu example doesn't work with KeyboardAdapter. When I select a submenu it just freezes. Have you experienced that?

**Comment by ShishkinDmitriy** [comment]
Yes, but I tought it's because of my local changes. I will check.

**Review by ShishkinDmitriy — APPROVED** [review]

**Comment by forntoh** [comment]
@ShishkinDmitriy Okay, will merge this once you identify the issue.

**Comment by forntoh** [comment]
@ShishkinDmitriy FYI: Seems like a general problem with `InputInterface`, even RotaryInput doesn't work with submenus.

**Comment by ShishkinDmitriy** [comment]
I think it should be fixed in #219

**Pull request merged**
