### PR TITLE
Feature/move control to items

### PR DESCRIPTION
**Pull request by ShishkinDmitriy**
Hi,

I have prepared some change to discuss.

## List of changes

- `MenuItem[]` do not leaked into `DisplayInterface`.
- Extracted `MenuScreen` to hold current cursor position, now it's possible to create multiple hierarchy menu. Currently only 2 supported, as I can see (only current and previous values are stored).
- Moved logic into `MenuItem` implementations and removed `switch`'s based on type, remove some `#ifdef`'s based on type. Now strict order of `#include` is not required.
- Extracted `ActionHandler`.
- Also `type` field can be eliminated - nothing depends on type now.

class diagram

- `LcdMenu` behave as facade and holds only current screen and enabled flag.
- `MenuScreen` controls scrolling of items, previously `LcdMenu` did it.
- implementations of `MenuItem` responsible for rendering on display, possibly can have state and have different behaviour based on the state. As implementation details are in `MenuItem` now it's possible to create custom implementation. As an example `ItemBack` was created.

I am ready to answer all questions and add changes if necessary.

Best regards,
Dmitry

### CODE REVIEW

**Comment by ShishkinDmitriy** [comment]
Hi, @forntoh, sure, I can split into small chunks and change examples.
If you create a branch it will be great.

**Comment by forntoh** [comment]
Created https://github.com/forntoh/LcdMenu/tree/feature/move-control-to-items

**Comment by forntoh** [comment]
Hi @ShishkinDmitriy 
Just wanted to leave a comment regarding this

> Extracted MenuScreen to hold current cursor position, now it's possible to create multiple hierarchy menu. Currently only 2 supported, as I can see (only current and previous values are stored).

Currently you can have more than one sub menu (an endless amount of sub menus, a sub menu in a sub menu), just that the example in the repo only shows one level, any number of sub menus and levels is possible as long as the microcontroller has the memory to support it.

I hope that's what the comment meant, at least that's what I understood.

**Comment by ShishkinDmitriy** [comment]
Hi, yes, true, but `LcdMenu` stores pointers and cursor only for the last one. What happened, if you will have 1 menu with 1 item, then submenu with 8 items and another submenu with 1 item and try to navigate from the last to first with `back`. You will execute `back` twice and wrong values for `previousXXX` will be applied. 

Maybe it's not so important for embedded system and need just to protect pointers from overlflow, not sure

**Comment by ShishkinDmitriy** [comment]
So wat do you think, worth it to extract `MenuScreen` from `LcdMenu`? 
It wil be replacement of `ItemHeader`. Also `ItemFooter` can be replaced with just NULL, what do you think?

**Comment by forntoh** [comment]
> So wat do you think, worth it to extract `MenuScreen` from `LcdMenu`? It wil be replacement of `ItemHeader`. 
> 
> Also `ItemFooter` can be replaced with just NULL, what do you think?

If you can do it without increasing the complexity of creating a menu then go for it, users of this lib enjoy the simplicity of instantiating a menu.
One objective you should have while doing this is to at least compile the existing examples without making any changes, it will also be easier for users when they upgrade it will just work.

**Pull request closed without merging**
