### PR TITLE
Feature/move control to items

### PR DESCRIPTION
**Pull request by ShishkinDmitriy**
As feature branch is stable we can merge it to master.

### CODE REVIEW

**Comment by forntoh** [comment]
@ShishkinDmitriy Everything has to be ready before this can be merged and released, documentation needs to be updated. If you see the milestone, I set latest date to release this to November 8 (of course, it can be released earlier).
Feel free to work on other improvements that can go into this release, like the one you mentioned in the discussions, in the meantime, I'll mark this as draft.

FYI: There's still one issue with ItemInput, I will create an issue for it, it's not a blocking issue but if it can be fixed before November 8 that'll be ideal.

Thanks for all the amazing improvements, the library has become much better.

**Comment by ShishkinDmitriy** [comment]
Ok, sure. I just didn't understand your flow.
Should I merge everything on this branch for now?
If yes, can you create branch for me `feature/use-ascii-symbols-for-control` and I will create PR to `feature/move-control-to-items`.

About documentation, yes, I can, not sure can spend much time, but let's try.

**Comment by forntoh** [comment]
You can keep merging into this feature branch. Just fork it and do your changes the target this branch. You don't need another feature branch.

**Comment by ShishkinDmitriy** [comment]
> I'll need your email address to send you an invitation

It's dimoninax@gmail.com

**Comment by milosh-dev** [comment]
That's a very neat decoupling and cleanup of the lcdMenu library!

Unfortunately, I didn't find the branch earlier and ended up working on a similar decoupling in parallel. I see many overlaps with my own code, as well as several solutions that are much more elegantly implemented!

However, I have one theoretical question, as I approached it differently. Why did you keep the isEditModeEnabled in the DisplayInterface? From a pure decoupling point of view, the question of whether a MenuItem is in edit mode doesn’t seem to belong in the DisplayInterface. I delegated the edit mode check down to the MenuItem class (where I believe it fits better) and addressed the blinker logic during the menu-building process by polling the active item to determine whether and where the blinker is needed. The original approach of calling display->getEditModeEnabled() from MenuItem always seemed bizarre to me. If needed, I can contribute this adjustment to the code (though I can't at the moment due to family-related tasks). :)

Overall, I fully support the merge!

(P.S. My next idea was to replace the const char* texts with PROGMEM.)

**Comment by ShishkinDmitriy** [comment]
Hi, I agree, it's strange to check edit mode from display. It's like reading the color of particular pixel on display and build logic based on it. 

I didn't touch it because I can't answer on some questions:
- if you store editMode state inside item, you store N booleans, but only 1 item can be true, so instead of multiple bool flags maybe would be better to use just single pointer on item under edit mode, but in this case you leak internal info of item outside (not all items have edit mode, but some have 2 edit modes);
- I didn't find the way to eliminate edit state from display - it's needed to know what arrow to draw. It means you need to store edit mode twice - in item and in display. 
- looks like it's used outside, then all items should expose 'isEditMode' method even if they have no edit mode.

**Comment by forntoh** [comment]
@milosh-dev In embedded systems, we're always aiming to minimize memory usage while maximizing functionality. As @ShishkinDmitriy pointed out, adding an edit mode flag to each `MenuItem` would significantly increase memory consumption, especially with many items, since each item would need an extra byte to store its edit state. Given that only one item can be in edit mode at a time, this approach isn't optimal if we want to be as memory-efficient as possible.

If you can think of a way to lift this out of `DisplayInterface` while maintaining a low memory footprint, feel free to submit a PR ☺️.

> Overall, I'm fully on board with this merge!

Shoutout to @ShishkinDmitriy for kickstarting this 💪—so many great ideas followed! I was a bit stuck and could only make incremental updates, but now my head's buzzing with possibilities 😃. For `v5.0.0`, we're done with new features—only documentation updates and critical bug fixes will be merged, and there's a lot to document 😓. This might even take the rest of the year to finish.

> (P.S. My next idea was to replace `const char*` texts with `PROGMEM`.)

@milosh-dev Feel free to branch off and start working on that 🚀!

**Review by forntoh — APPROVED** [review]

**Pull request merged**
